version: "3.7"
services:
 nginx:
  image: felixgreen/cinema-interface-nginx-docker
  ports:
  - 80:80
  - 443:443
  volumes:
  - ../media:/media
  - ../static:/static
  - /etc/letsencrypt:/etc/letsencrypt
 tarantool:
  image: felixgreen/teamproject_tarantool_image
  ports:
   - 3301:3301
  volumes:
   - ~/data/tarantool:/var/lib/tarantool
 app:
  image: felixgreen/cinema_interfaceservice_image
  ports:
   - 8080:8080
  volumes:
   - ./:/app
   - ../media:/media
 postgresql:
  image: postgres
  ports:
  - 5432:5432
  restart: always
  env_file:
   - ./init/database.env
  healthcheck:
   test: CMD pg_isready -U $POSTGRES_USER
  volumes:
   - ./init/:/docker-entrypoint-initdb.d/
   - ~/etc/postgresql:/etc/postgresql
   - ~/var/log/postgresql:/var/log/postgresql
   - ~/var/lib/postgresql:/var/lib/postgresql
   - ~/var/lib/postgresql/data:/var/lib/postgresql/data/:rw
