version: "3.7"
services:
 nginx:
  image: felixgreen/cinema-interface-nginx-docker
  restart: on-failure
  ports:
  - 80:80
  - 443:443
  volumes:
  - /home/ubuntu/media:/media
  - /home/ubuntu/static:/static
  - /home/ubuntu/etc/letsencrypt:/etc/letsencrypt
 tarantool:
  image: felixgreen/teamproject_tarantool_image
  ports:
   - 3301:3301
  volumes:
   - /home/ubuntu/data/tarantool:/var/lib/tarantool
 postgresql:
  image: postgres
  ports:
  - 5432:5432
  restart: always
  env_file:
   - ./init/database.env
  volumes:
   - ./init/:/docker-entrypoint-initdb.d/
   - /home/ubuntu/etc/postgresql:/etc/postgresql
   - /home/ubuntu/var/log/postgresql:/var/log/postgresql
   - /home/ubuntu/var/lib/postgresql:/var/lib/postgresql
   - /home/ubuntu/var/lib/postgresql/data:/var/lib/postgresql/data/:rw
 app:
  image: felixgreen/cinema_interfaceservice_image
  restart: always
  ports:
   - 8080:8080
  volumes:
   - /home/ubuntu/media:/media
   - ./:/app
 auth:
  image: felixgreen/cinema-auth-service
  restart: always
  ports:
   - 8082:8082
  volumes:
   - /home/ubuntu/media:/media
 profile:
  image: felixgreen/cinema-profile-service
  restart: always
  ports:
   - 8081:8081
  volumes:
   - /home/ubuntu/media:/media
# prometheus:
#  image: prom/prometheus
#  restart: on-failure
#  ports:
#  - 9090:9090
#  volumes:
#   - ./prometheus.yml:/etc/prometheus/prometheus.yml
# grafana:
#  image: grafana/grafana
#  restart: on-failure
#  ports:
#  - 3000:3000