version: "3.7"
services:
 nginx:
  image: felixgreen/cinema-interface-nginx-docker
  ports:
  - 80:80
  - 443:443
  volumes:
  - ../media:/media
  - ../static:/static
  - /etc/letsencrypt:/etc/letsencrypt
 tarantool:
  image: felixgreen/teamproject_tarantool_image
  ports:
   - 3301:3301
  volumes:
   - /data/tarantool:/var/lib/tarantool
 app:
  image: felixgreen/cinema_interfaceservice_image
  ports:
   - 8080:8080
  volumes:
   - ./:/app
   - ../media:/media
 postgresql:
  image: felixgreen/cinema_postgres_image
  ports:
  - 5432:5432
  volumes:
   - ./init/:/docker-entrypoint-initdb.d/
   - /etc/postgresql:/etc/postgresql
   - /var/log/postgresql:/var/log/postgresql
   - /var/lib/postgresql:/var/lib/postgresql
