// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson9643cb81DecodeGithubComGoParkMailRu20202JigglypufInternalPkgModels(in *jlexer.Lexer, out *RecommendationDataFrame) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "UserID":
			out.UserID = uint64(in.Uint64())
		case "MovieName":
			out.MovieName = string(in.String())
		case "MovieID":
			out.MovieID = uint64(in.Uint64())
		case "UserRating":
			out.UserRating = int(in.Int())
		case "MovieRating":
			out.MovieRating = float64(in.Float64())
		case "MovieRatingCount":
			out.MovieRatingCount = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9643cb81EncodeGithubComGoParkMailRu20202JigglypufInternalPkgModels(out *jwriter.Writer, in RecommendationDataFrame) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"UserID\":"
		out.RawString(prefix[1:])
		out.Uint64(uint64(in.UserID))
	}
	{
		const prefix string = ",\"MovieName\":"
		out.RawString(prefix)
		out.String(string(in.MovieName))
	}
	{
		const prefix string = ",\"MovieID\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.MovieID))
	}
	{
		const prefix string = ",\"UserRating\":"
		out.RawString(prefix)
		out.Int(int(in.UserRating))
	}
	{
		const prefix string = ",\"MovieRating\":"
		out.RawString(prefix)
		out.Float64(float64(in.MovieRating))
	}
	{
		const prefix string = ",\"MovieRatingCount\":"
		out.RawString(prefix)
		out.Int(int(in.MovieRatingCount))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RecommendationDataFrame) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9643cb81EncodeGithubComGoParkMailRu20202JigglypufInternalPkgModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RecommendationDataFrame) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9643cb81EncodeGithubComGoParkMailRu20202JigglypufInternalPkgModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RecommendationDataFrame) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9643cb81DecodeGithubComGoParkMailRu20202JigglypufInternalPkgModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RecommendationDataFrame) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9643cb81DecodeGithubComGoParkMailRu20202JigglypufInternalPkgModels(l, v)
}
