// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonEc4a53ffDecodeGithubComGoParkMailRu20202JigglypufInternalPkgModels(in *jlexer.Lexer, out *Schedule) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "ID":
			out.ID = uint64(in.Uint64())
		case "MovieID":
			out.MovieID = uint64(in.Uint64())
		case "CinemaID":
			out.CinemaID = uint64(in.Uint64())
		case "HallID":
			out.HallID = uint64(in.Uint64())
		case "PremierTime":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.PremierTime).UnmarshalJSON(data))
			}
		case "Cost":
			out.Cost = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonEc4a53ffEncodeGithubComGoParkMailRu20202JigglypufInternalPkgModels(out *jwriter.Writer, in Schedule) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"ID\":"
		out.RawString(prefix[1:])
		out.Uint64(uint64(in.ID))
	}
	{
		const prefix string = ",\"MovieID\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.MovieID))
	}
	{
		const prefix string = ",\"CinemaID\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.CinemaID))
	}
	{
		const prefix string = ",\"HallID\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.HallID))
	}
	{
		const prefix string = ",\"PremierTime\":"
		out.RawString(prefix)
		out.Raw((in.PremierTime).MarshalJSON())
	}
	{
		const prefix string = ",\"Cost\":"
		out.RawString(prefix)
		out.Int(int(in.Cost))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Schedule) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonEc4a53ffEncodeGithubComGoParkMailRu20202JigglypufInternalPkgModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Schedule) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonEc4a53ffEncodeGithubComGoParkMailRu20202JigglypufInternalPkgModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Schedule) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonEc4a53ffDecodeGithubComGoParkMailRu20202JigglypufInternalPkgModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Schedule) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonEc4a53ffDecodeGithubComGoParkMailRu20202JigglypufInternalPkgModels(l, v)
}
