// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
	http "net/http"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6787350aDecodeGithubComGoParkMailRu20202JigglypufInternalPkgModels(in *jlexer.Lexer, out *DBResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "ID":
			out.ID = uint64(in.Uint64())
		case "CookieValue":
			out.CookieValue = string(in.String())
		case "UserID":
			out.UserID = uint64(in.Uint64())
		case "Cookie":
			easyjson6787350aDecodeNetHttp(in, &out.Cookie)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6787350aEncodeGithubComGoParkMailRu20202JigglypufInternalPkgModels(out *jwriter.Writer, in DBResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"ID\":"
		out.RawString(prefix[1:])
		out.Uint64(uint64(in.ID))
	}
	{
		const prefix string = ",\"CookieValue\":"
		out.RawString(prefix)
		out.String(string(in.CookieValue))
	}
	{
		const prefix string = ",\"UserID\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.UserID))
	}
	{
		const prefix string = ",\"Cookie\":"
		out.RawString(prefix)
		easyjson6787350aEncodeNetHttp(out, in.Cookie)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v DBResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6787350aEncodeGithubComGoParkMailRu20202JigglypufInternalPkgModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v DBResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6787350aEncodeGithubComGoParkMailRu20202JigglypufInternalPkgModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *DBResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6787350aDecodeGithubComGoParkMailRu20202JigglypufInternalPkgModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *DBResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6787350aDecodeGithubComGoParkMailRu20202JigglypufInternalPkgModels(l, v)
}
func easyjson6787350aDecodeNetHttp(in *jlexer.Lexer, out *http.Cookie) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Name":
			out.Name = string(in.String())
		case "Value":
			out.Value = string(in.String())
		case "Path":
			out.Path = string(in.String())
		case "Domain":
			out.Domain = string(in.String())
		case "Expires":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.Expires).UnmarshalJSON(data))
			}
		case "RawExpires":
			out.RawExpires = string(in.String())
		case "MaxAge":
			out.MaxAge = int(in.Int())
		case "Secure":
			out.Secure = bool(in.Bool())
		case "HttpOnly":
			out.HttpOnly = bool(in.Bool())
		case "SameSite":
			out.SameSite = http.SameSite(in.Int())
		case "Raw":
			out.Raw = string(in.String())
		case "Unparsed":
			if in.IsNull() {
				in.Skip()
				out.Unparsed = nil
			} else {
				in.Delim('[')
				if out.Unparsed == nil {
					if !in.IsDelim(']') {
						out.Unparsed = make([]string, 0, 4)
					} else {
						out.Unparsed = []string{}
					}
				} else {
					out.Unparsed = (out.Unparsed)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					v1 = string(in.String())
					out.Unparsed = append(out.Unparsed, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6787350aEncodeNetHttp(out *jwriter.Writer, in http.Cookie) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"Value\":"
		out.RawString(prefix)
		out.String(string(in.Value))
	}
	{
		const prefix string = ",\"Path\":"
		out.RawString(prefix)
		out.String(string(in.Path))
	}
	{
		const prefix string = ",\"Domain\":"
		out.RawString(prefix)
		out.String(string(in.Domain))
	}
	{
		const prefix string = ",\"Expires\":"
		out.RawString(prefix)
		out.Raw((in.Expires).MarshalJSON())
	}
	{
		const prefix string = ",\"RawExpires\":"
		out.RawString(prefix)
		out.String(string(in.RawExpires))
	}
	{
		const prefix string = ",\"MaxAge\":"
		out.RawString(prefix)
		out.Int(int(in.MaxAge))
	}
	{
		const prefix string = ",\"Secure\":"
		out.RawString(prefix)
		out.Bool(bool(in.Secure))
	}
	{
		const prefix string = ",\"HttpOnly\":"
		out.RawString(prefix)
		out.Bool(bool(in.HttpOnly))
	}
	{
		const prefix string = ",\"SameSite\":"
		out.RawString(prefix)
		out.Int(int(in.SameSite))
	}
	{
		const prefix string = ",\"Raw\":"
		out.RawString(prefix)
		out.String(string(in.Raw))
	}
	{
		const prefix string = ",\"Unparsed\":"
		out.RawString(prefix)
		if in.Unparsed == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Unparsed {
				if v2 > 0 {
					out.RawByte(',')
				}
				out.String(string(v3))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}
