// Code generated by MockGen. DO NOT EDIT.
// Source: CookieUseCase.go

// Package mock is a generated GoMock package.
package mock

import (
	gomock "github.com/golang/mock/gomock"
	http "net/http"
	reflect "reflect"
)

// MockUseCase is a mock of UseCase interface
type MockUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUseCaseMockRecorder
}

// MockUseCaseMockRecorder is the mock recorder for MockUseCase
type MockUseCaseMockRecorder struct {
	mock *MockUseCase
}

// NewMockUseCase creates a new mock instance
func NewMockUseCase(ctrl *gomock.Controller) *MockUseCase {
	mock := &MockUseCase{ctrl: ctrl}
	mock.recorder = &MockUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUseCase) EXPECT() *MockUseCaseMockRecorder {
	return m.recorder
}

// CheckCookie mocks base method
func (m *MockUseCase) CheckCookie(cookieValue *http.Cookie) (uint64, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckCookie", cookieValue)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// CheckCookie indicates an expected call of CheckCookie
func (mr *MockUseCaseMockRecorder) CheckCookie(cookieValue interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckCookie", reflect.TypeOf((*MockUseCase)(nil).CheckCookie), cookieValue)
}

// RemoveCookie mocks base method
func (m *MockUseCase) RemoveCookie(cookieValue *http.Cookie) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveCookie", cookieValue)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveCookie indicates an expected call of RemoveCookie
func (mr *MockUseCaseMockRecorder) RemoveCookie(cookieValue interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveCookie", reflect.TypeOf((*MockUseCase)(nil).RemoveCookie), cookieValue)
}

// SetCookie mocks base method
func (m *MockUseCase) SetCookie(cookieValue *http.Cookie, UserID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCookie", cookieValue, UserID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetCookie indicates an expected call of SetCookie
func (mr *MockUseCaseMockRecorder) SetCookie(cookieValue, UserID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCookie", reflect.TypeOf((*MockUseCase)(nil).SetCookie), cookieValue, UserID)
}
